### Fetch all messages
GET http://localhost:3000/api/v1/forum

### Create a post
POST http://localhost:3000/api/v1/forum/post/janedoe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJqYW5lZG9lIiwidXNlcl90eXBlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NDY0MjU3NDAsImV4cCI6MTc0NjUxMjE0MH0.dPx_v4TUKJqnGzwYdBTklyp_WmKH9iWYtJKHvv9UrAw
Content-Type: application/json

{
    "title": "My first post",
    "message": "loren lipsum"
}

### Reply to a post
POST http://localhost:3000/api/v1/forum/post/9/janedoe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJqYW5lZG9lIiwidXNlcl90eXBlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NDY0MjU3NDAsImV4cCI6MTc0NjUxMjE0MH0.dPx_v4TUKJqnGzwYdBTklyp_WmKH9iWYtJKHvv9UrAw
Content-Type: application/json

{
    "title": "My first post",
    "message": "loren lipsum"
}
