### Fetch menu info
GET http://localhost:3000/api/v1/info/menu/fi

### Fetch item info
GET http://localhost:3000/api/v1/info/menu/item/4

### Fetch allergen info
GET http://localhost:3000/api/v1/info/allergens/fi

### Fetch restaurant info
GET http://localhost:3000/api/v1/info/restaurant/fi

### Fetch game info
GET http://localhost:3000/api/v1/info/boardgames/fi

### Fetch food category info
GET http://localhost:3000/api/v1/info/itemcategories/fi

### Fetch game category info
GET http://localhost:3000/api/v1/info/gamecategories/fi

### Fetch public translation info
GET http://localhost:3000/api/v1/info/getPublicTransport



### Change restaurant phone
POST http://localhost:3000/api/v1/info/restaurant/phone/10123456786

### Change restaurant email
POST http://localhost:3000/api/v1/info/restaurant/email/demo@metropolia.com

### Change restaurant open times
POST http://localhost:3000/api/v1/info/restaurant/open/9am-10pm

10123456789
9am-9pm
demo@gmail.com
