### Fetch menu info
GET http://localhost:3000/api/v1/info/menu/fi

### Fetch item info
GET http://localhost:3000/api/v1/info/menu/item/4

### Fetch allergen info
GET http://localhost:3000/api/v1/info/allergens/fi

### Fetch restaurant info
GET http://localhost:3000/api/v1/info/restaurant/fi

### Fetch game info
GET http://localhost:3000/api/v1/info/boardgames/fi

### Fetch food category info
GET http://localhost:3000/api/v1/info/itemcategories/fi

### Fetch game category info
GET http://localhost:3000/api/v1/info/gamecategories/fi

### Fetch public translation info
GET http://localhost:3000/api/v1/info/getPublicTransport



### Change restaurant phone
POST http://localhost:3000/api/v1/info/restaurant/phone/10123456784
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsInVzZXJuYW1lIjoiYWRtaW4iLCJ1c2VyX3R5cGUiOiJhZG1pbiIsImlhdCI6MTc0NjUxOTE0NCwiZXhwIjoxNzQ2NjA1NTQ0fQ.7xyN9uw4cAdcIiYoOe-tCEOZsNY7lpFh9OnQwNCpXTg

### Change restaurant email
POST http://localhost:3000/api/v1/info/restaurant/email/demo@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsInVzZXJuYW1lIjoiYWRtaW4iLCJ1c2VyX3R5cGUiOiJhZG1pbiIsImlhdCI6MTc0NjUxOTE0NCwiZXhwIjoxNzQ2NjA1NTQ0fQ.7xyN9uw4cAdcIiYoOe-tCEOZsNY7lpFh9OnQwNCpXTg

### Change restaurant open times
POST http://localhost:3000/api/v1/info/restaurant/open/9am-9pm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsInVzZXJuYW1lIjoiYWRtaW4iLCJ1c2VyX3R5cGUiOiJhZG1pbiIsImlhdCI6MTc0NjUxOTE0NCwiZXhwIjoxNzQ2NjA1NTQ0fQ.7xyN9uw4cAdcIiYoOe-tCEOZsNY7lpFh9OnQwNCpXTg


10123456789
9am-9pm
demo@gmail.com
