### Fetch all orders
GET http://localhost:3000/api/v1/orders

### Fetch specific order ny id
GET http://localhost:3000/api/v1/orders/10

### Create a new order
POST http://localhost:3000/api/v1/orders/robdoe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsInVzZXJuYW1lIjoicm9iZG9lIiwiaWF0IjoxNzQ1OTA5MjQwLCJleHAiOjE3NDU5OTU2NDB9.0GEMwICaELs6PWnJ3Dp8-_Oy0iP07ewBSYucqsLylHo
Content-Type: application/json

{
  "order": [
    {"item_id": 6,
    "quantity": 1},
    {"item_id": 9,
    "quantity": 5},
    {"item_id": 10,
    "quantity": 2}
  ]
}

### Change order status
POST http://localhost:3000/api/v1/orders/status
Authorization: Bearer Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsInVzZXJuYW1lIjoicm9iZG9lIiwiaWF0IjoxNzQ1OTA5MjQwLCJleHAiOjE3NDU5OTU2NDB9.0GEMwICaELs6PWnJ3Dp8-_Oy0iP07ewBSYucqsLylHo
Content-Type: application/json

Valid statuses: pending, confirmed, ready, completed, cancelled

{
  "order_id" : "4",
  "status" : "ready"
  }


### Add item to menu
POST http://localhost:3000/api/v1/orders/menu
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsInVzZXJuYW1lIjoiYWRtaW4iLCJ1c2VyX3R5cGUiOiJhZG1pbiIsImlhdCI6MTc0NjQzMjY4OCwiZXhwIjoxNzQ2NTE5MDg4fQ.DqiJ3FV6nmKM0K0XDlGiaXL4aA78bIaQbRrDrzpXBsc
Content-Type: application/json

{
  "menu_item": {
    "name": "Testi",
    "price": 5055.00,
    "categories": [2,3],
    "description": "Testi testi",
    "allergens": [2, 3],
    "lang": "en"
  }
}

### Delete item from menu
DELETE http://localhost:3000/api/v1/orders/menu/129
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsInVzZXJuYW1lIjoiYWRtaW4iLCJ1c2VyX3R5cGUiOiJhZG1pbiIsImlhdCI6MTc0NjQzMjY4OCwiZXhwIjoxNzQ2NTE5MDg4fQ.DqiJ3FV6nmKM0K0XDlGiaXL4aA78bIaQbRrDrzpXBsc

