### Fetch all orders
GET http://localhost:3000/api/v1/orders

### Fetch specific order ny id
GET http://localhost:3000/api/v1/orders/5

### Create a new order
POST http://localhost:3000/api/v1/orders/janedoe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImphbmVkb2UiLCJpYXQiOjE3NDU5MDYxMjIsImV4cCI6MTc0NTk5MjUyMn0.eNAKyjX3sAdgu3iWE2GArzP5xLzfDc8MuZjHHqPvZk8
Content-Type: application/json

{
  "customer_id": 1,
  "order": [
    {"item_id": 6,
    "quantity": 1},
    {"item_id": 9,
    "quantity": 5},
    {"item_id": 10,
    "quantity": 2}
  ]
}
