### Fetch all table reservations
GET http://localhost:3000/api/v1/tables

### Fetch all tables
GET http://localhost:3000/api/v1/tables/tables

### Create a new reservation
POST http://localhost:3000/api/v1/tables/reserve/robdoe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsInVzZXJuYW1lIjoicm9iZG9lIiwiaWF0IjoxNzQ1OTA5MjQwLCJleHAiOjE3NDU5OTU2NDB9.0GEMwICaELs6PWnJ3Dp8-_Oy0iP07ewBSYucqsLylHo
Content-Type: application/json

{
  "customer_id": 1,
  "reservation": {
    "arrival_time": "2025-04-29 09:12:09",
    "departure_time": "2025-04-29 09:14:09",
    "reservation_size": 4,
    "additional_information": "Window seat, no smoking",
    "tables": [
      {"table_id": 3},
      {"table_id": 4},
      {"table_id": 5}
    ]
  }
}
