### Create a new user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "username": "bobdoe",
  "password": "pass",
  "email": "bob@metropolia.fi"
}

### Get a specific user details by ID (no password information), order ids included
GET http://localhost:3000/api/v1/users/1
Content-Type: application/json

### Login to a specific user by ID
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "janedoe",
  "password": "pass"
}

### Login to a specific user by ID with incorrect password
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "janedoe",
  "password": "123"
}

### token test
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbmVkb2UiLCJpYXQiOjE3NDU2NTk3NTksImV4cCI6MTc0NTc0NjE1OX0.Iu5Oo8ovBcYS97QWeJYwrVkRqLYvTRuh8ybyytBdvTg

### test sending a file
POST http://localhost:3000/api/v1/users/img/bobdoe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbmVkb2UiLCJpYXQiOjE3NDU2NTk3NTksImV4cCI6MTc0NTc0NjE1OX0.Iu5Oo8ovBcYS97QWeJYwrVkRqLYvTRuh8ybyytBdvTg
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="150.jpg"
Content-Type: image/jpeg

< ../../../150.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
