### Create a new user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "username": "robdoe",
  "password": "pass",
  "email": "rob@metropolia.fi"
}

### Get a specific user details by ID (no password information), order ids included
GET http://localhost:3000/api/v1/users/14
Content-Type: application/json

### Login to a specific user by ID
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "janedoe",
  "password": "pass"
}

### Login to a specific user by ID with incorrect password
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "janedoe",
  "password": "123"
}

### token test
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsInVzZXJuYW1lIjoicm9iZG9lIiwiaWF0IjoxNzQ1OTA5MjQwLCJleHAiOjE3NDU5OTU2NDB9.0GEMwICaELs6PWnJ3Dp8-_Oy0iP07ewBSYucqsLylHo

### test sending a file
POST http://localhost:3000/api/v1/users/img/robdoe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsInVzZXJuYW1lIjoicm9iZG9lIiwiaWF0IjoxNzQ1OTA5MjQwLCJleHAiOjE3NDU5OTU2NDB9.0GEMwICaELs6PWnJ3Dp8-_Oy0iP07ewBSYucqsLylHo
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="150.jpg"
Content-Type: image/jpeg

< ../../../150.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Modify user test
PUT http://localhost:3000/api/v1/users/9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwidXNlcm5hbWUiOiJuZXdwcnVkb2UiLCJpYXQiOjE3NDYwMDEyMTcsImV4cCI6MTc0NjA4NzYxN30.ke20bX7xPeah8aCIBww99wxB8grd5VfDMxFmNnjyf80

Example body:

{
  "username": "prudoethebest",
  "email" : "editpru@email.eu",
  "password": "newpass"
}
